#ifndef UI_CONSTANTS_H
#define UI_CONSTANTS_H

#include "lvgl.h"

#define COLOR_BACKGROUND_GREEN lv_color_make(124, 218, 124)
#define DEFAULT_OVERHEAD_GAP 200
#define DEFAULT_PERIOD 200

// Alert
#define SCARY_RED lv_color_hex(0xFF6666)

// Screens
#define SCREEN_ANIM_TIME 300

// Chart
#define CHART_WIDTH 260
#define CHART_HEIGHT 160
#define CHART_POINT_COUNT 80
#define CHART_SPEED_POINT_COUNT 160

// Speed
#define SENSOR_SPEED_YMIN 0
#define SENSOR_SPEED_YMAX 1500
#define SENSOR_SPEED_OVERHEADGAP 250
#define SENSOR_SPEED_PERIOD 50

// Acceleration
#define SENSOR_ACCELERATION_YMIN 0
#define SENSOR_ACCELERATION_YMAX 4000
#define SENSOR_ACCELERATION_OVERHEADGAP 250
#define SENSOR_ACCELERATION_PERIOD 250

// Power
#define SENSOR_POWER_YMIN 0
#define SENSOR_POWER_YMAX 30
#define SENSOR_POWER_OVERHEADGAP 5
#define SENSOR_POWER_PERIOD 250

// Light
#define SENSOR_LIGHT_YMIN 0
#define SENSOR_LIGHT_YMAX 1000
#define SENSOR_LIGHT_OVERHEADGAP 250
#define SENSOR_LIGHT_PERIOD 250

#define SENSOR_DISTANCE_YMIN 0
#define SENSOR_DISTANCE_YMAX 20
#define SENSOR_DISTANCE_OVERHEADGAP 5
#define SENSOR_DISTANCE_PERIOD 250

// Speedometer
#define SPEEDO_SCALE_RADIUS 70
#define SPEEDO_NEEDLE_LENGTH 60
#define SPEEDO_PERIOD 50
#define NEEDLE_ANIM_TIME 100
// Humidity
#define SENSOR_HUMIDITY_SCALE_RADIUS 90
#define SENSOR_HUMIDITY_NEEDLE_LENGTH 70
#define SENSOR_HUMIDITY_PERIOD 250

// STATUS
#define STATUS_CARD_BG 0x1E293B
#define STATUS_CARD_WIDTH 140
#define STATUS_CARD_HEIGHT 75

#endif