#define POWER_SENSOR_EVENT (1 << 0)
#define SPEED_SENSOR_EVENT (1 << 1)
#define LIGHT_SENSOR_EVENT (1 << 2)
#define ACCEL_SENSOR_EVENT (1 << 3)
#define TEMP_SENSOR_EVENT (1 << 4)
#define DIST_SENSOR_EVENT (1 << 5)

#define ALL_SENSOR_EVENTS (POWER_SENSOR_EVENT | SPEED_SENSOR_EVENT | LIGHT_SENSOR_EVENT | ACCEL_SENSOR_EVENT | TEMP_SENSOR_EVENT | DIST_SENSOR_EVENT)
